<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPNJY4Qx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPNJY4Qx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPNJY4Qx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPNJY4Qx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPNJY4Qx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PNJY4Qx',
    'container.build_id' => 'fefb9eec',
    'container.build_time' => 1553111335,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPNJY4Qx');
