<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAXWdW0D\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAXWdW0D/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAXWdW0D.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAXWdW0D\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAXWdW0D\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AXWdW0D',
    'container.build_id' => 'b4b07d31',
    'container.build_time' => 1553176790,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAXWdW0D');
