<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKE1rS2c\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKE1rS2c/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKE1rS2c.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKE1rS2c\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKE1rS2c\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KE1rS2c',
    'container.build_id' => '396b013f',
    'container.build_time' => 1550758982,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKE1rS2c');
